
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: strapi
      # Use a strong password here, and match it below and in Coolify. Sets the password for the Postgres database user (strapi)
      POSTGRES_PASSWORD: strongpassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - strapi-network

  strapi:
    build: ./server
    ports:
      - '1337:1337'
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432 # Good practice to be explicit
      - DATABASE_NAME=restaurant_db
      # --- FIX THIS LINE ---
      - DATABASE_USERNAME=strapi
      # --- END FIX ---
      - DATABASE_PASSWORD=strongpassword123 # Must match postgres service above. Password for Strapi to connect to Postgres
      # --- SECRETS - Use secure values --
      - JWT_SECRET=generate_a_strong_random_secret_here_for_users
      - ADMIN_JWT_SECRET=generate_a_different_strong_secret_for_admin
      - APP_KEYS=generate_comma_separated_keys_1,generate_comma_separated_keys_2
      - API_TOKEN_SALT=generate_another_strong_random_salt
      - TRANSFER_TOKEN_SALT=generate_yet_another_strong_random_salt
    depends_on:
      - postgres
    networks:
      - strapi-network

  nextjs:
    build: ./client
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_STRAPI_URL=http://strapi:1337
    depends_on:
      - strapi
    networks:
      - strapi-network

volumes:
  postgres_data:

networks:
  strapi-network: